// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtY_z9v0J2REVWDavQqtG9TeUYgpxEouY',
    appId: '1:124692845363:web:d53bb62cdbd6fd151ae446',
    messagingSenderId: '124692845363',
    projectId: 'tpflutter-b46d3',
    authDomain: 'tpflutter-b46d3.firebaseapp.com',
    storageBucket: 'tpflutter-b46d3.firebasestorage.app',
    measurementId: 'G-PPH07KHM89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRp42QpNi_x8xZpp9mjnvb8XmBYgYxSys',
    appId: '1:124692845363:android:6ffef8f9b0eeb1981ae446',
    messagingSenderId: '124692845363',
    projectId: 'tpflutter-b46d3',
    storageBucket: 'tpflutter-b46d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClS8UrqXJ6gheciFSsTjS5eQheqPDoKt0',
    appId: '1:124692845363:ios:e3e46b4651cdf24a1ae446',
    messagingSenderId: '124692845363',
    projectId: 'tpflutter-b46d3',
    storageBucket: 'tpflutter-b46d3.firebasestorage.app',
    androidClientId: '124692845363-ghb5o5n3v1q6qgv970vadp8ljkii8kp7.apps.googleusercontent.com',
    iosClientId: '124692845363-t5v7hf5lr3tdkt68cb82kk1ih6o4su4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClS8UrqXJ6gheciFSsTjS5eQheqPDoKt0',
    appId: '1:124692845363:ios:e3e46b4651cdf24a1ae446',
    messagingSenderId: '124692845363',
    projectId: 'tpflutter-b46d3',
    storageBucket: 'tpflutter-b46d3.firebasestorage.app',
    androidClientId: '124692845363-ghb5o5n3v1q6qgv970vadp8ljkii8kp7.apps.googleusercontent.com',
    iosClientId: '124692845363-t5v7hf5lr3tdkt68cb82kk1ih6o4su4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtY_z9v0J2REVWDavQqtG9TeUYgpxEouY',
    appId: '1:124692845363:web:dc477987d1502eb81ae446',
    messagingSenderId: '124692845363',
    projectId: 'tpflutter-b46d3',
    authDomain: 'tpflutter-b46d3.firebaseapp.com',
    storageBucket: 'tpflutter-b46d3.firebasestorage.app',
    measurementId: 'G-Y9ZT3PQ373',
  );

}